name: 'tests'

on:
  push:
  pull_request:
    branches: ['main']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit:
    name: "unit"
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        container:
          - 'registry.opensuse.org/opensuse/tumbleweed'

    container:
      image: ${{ matrix.container }}

    steps:
      - name: 'Install packages'
        run: |
            zypper -n modifyrepo --disable repo-openh264 || :
            zypper -n --gpg-auto-import-keys refresh
            zypper -n install python3 python3-pip python3-pydantic python3-pytest python3-rpm python3-setuptools python3-solv python3-PyYAML

      - uses: actions/checkout@v4

      - name: 'Run unit tests'
        run: |
          pip3 config set global.break-system-packages 1
          pip3 install --no-dependencies -e .
          pytest tests
