name: 'tests'

on:
  pull_request:
    branches: ['main']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit:
    name: "unit"
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        # Testing per python-version using actions/setup-python is not possible,
        # because rpm doesn't exist on pypi and cannot be installed via pip on ubuntu.
        # That's why we're going to test on the target distros directly.
        container:

          - 'registry.opensuse.org/opensuse/leap:15.5'
          - 'registry.opensuse.org/opensuse/tumbleweed'

    container:
      image: ${{ matrix.container }}

    steps:
      - name: 'Set ENV variables (openSUSE Tumbleweed)'
        if: ${{ contains(matrix.container, '/opensuse/tumbleweed') }}
        env:
            PYTHON3_PKG=python3
            PYTHON3=python3

      - name: 'Set ENV variables (openSUSE Leap)'
        if: ${{ contains(matrix.container, '/opensuse/leap') }}
        env:
            PYTHON3_PKG=python311
            PYTHON3=python3.11

      - name: 'Install packages'
        run: |
            zypper -n modifyrepo --disable repo-openh264 || :
            zypper -n --gpg-auto-import-keys refresh
            zypper -n install ${PYTHON3_PKG} ${PYTHON3_PKG}-pip ${PYTHON3_PKG}-pydantic ${PYTHON3_PKG}-pytest ${PYTHON3_PKG}-rpm ${PYTHON3_PKG}-setuptools ${PYTHON3_PKG}-solv ${PYTHON3_PKG}-PyYAML

      - uses: actions/checkout@v4

      - name: 'Run unit tests'
        run: |
          pip3 config set global.break-system-packages 1
          pip3 install --no-dependencies -e .
          pytest tests
